# Generated by Django 3.0.6 on 2020-06-15 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import verses.custom_models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='verses.Tag')),
            ],
            options={
                'unique_together': {('level', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Tag1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('parent_tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='verses.Tag1')),
            ],
        ),
        migrations.CreateModel(
            name='Tag3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('parent_tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='verses.Tag2')),
            ],
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('verse_id', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('canto_num', models.IntegerField()),
                ('chapter_num', models.IntegerField()),
                ('verse_num', models.IntegerField()),
                ('verse_num_end', models.IntegerField(null=True)),
                ('verse', verses.custom_models.Text(max_length=1000)),
                ('synonyms', verses.custom_models.Text(max_length=5000)),
                ('devanagari', verses.custom_models.Text(max_length=1000)),
                ('translation', verses.custom_models.Text(max_length=1000)),
                ('purport', verses.custom_models.Text(max_length=40000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagRequest',
            fields=[
                ('verse_id', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=70)),
                ('parent', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tagrequest_approver', to=settings.AUTH_USER_MODEL)),
                ('initiator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tagrequest_initiator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TranslationTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagger_remark', models.CharField(max_length=1000, null=True)),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translation_reviewer', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(default='None', on_delete=django.db.models.deletion.SET_DEFAULT, to='verses.Tag3')),
                ('tag_name', models.ForeignKey(default='None', on_delete=django.db.models.deletion.SET_DEFAULT, to='verses.Tag')),
                ('tagger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translation_tagger', to=settings.AUTH_USER_MODEL)),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verses.Verse')),
            ],
            options={
                'unique_together': {('verse_id', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='PurportSectionTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_idx', models.IntegerField()),
                ('end_idx', models.IntegerField()),
                ('tagger_remark', models.CharField(max_length=1000, null=True)),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purport_reviewer', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(default='None', on_delete=django.db.models.deletion.SET_DEFAULT, to='verses.Tag3')),
                ('tag_name', models.ForeignKey(default='None', on_delete=django.db.models.deletion.SET_DEFAULT, to='verses.Tag')),
                ('tagger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purport_tagger', to=settings.AUTH_USER_MODEL)),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verses.Verse')),
            ],
            options={
                'unique_together': {('verse_id', 'tag', 'start_idx', 'end_idx')},
            },
        ),
    ]
