# Generated by Django 3.0.6 on 2020-05-15 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tag2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('parent_tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='verses.Tag1')),
            ],
        ),
        migrations.CreateModel(
            name='Tag3',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('parent_tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='verses.Tag2')),
            ],
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('verse_id', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('canto_num', models.IntegerField()),
                ('chapter_num', models.IntegerField()),
                ('verse_num', models.IntegerField()),
                ('verse', models.TextField(max_length=200)),
                ('translation', models.TextField(max_length=1000)),
                ('purport', models.TextField(max_length=40000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TranslationTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(default='None', on_delete=django.db.models.deletion.SET_DEFAULT, to='verses.Tag3')),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verses.Verse')),
            ],
        ),
        migrations.CreateModel(
            name='PurportSectionTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_idx', models.IntegerField()),
                ('end_idx', models.IntegerField()),
                ('tag', models.ForeignKey(default='None', on_delete=django.db.models.deletion.SET_DEFAULT, to='verses.Tag3')),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verses.Verse')),
            ],
        ),
    ]
