# Generated by Django 3.0.6 on 2020-05-28 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('verses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagRequest',
            fields=[
                ('verse_id', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=70, unique=True)),
                ('parent', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='purportsectiontag',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purport_reviewer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purportsectiontag',
            name='tagger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purport_tagger', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='translationtag',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translation_reviewer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='translationtag',
            name='tagger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translation_tagger', to=settings.AUTH_USER_MODEL),
        ),
    ]
