# Generated by Django 3.0.6 on 2020-05-15 07:46

from django.db import migrations
import verses.custom_models


class Migration(migrations.Migration):

    dependencies = [
        ('verses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verse',
            name='purport',
            field=verses.custom_models.Text(max_length=40000, null=True),
        ),
        migrations.AlterField(
            model_name='verse',
            name='translation',
            field=verses.custom_models.Text(max_length=1000),
        ),
        migrations.AlterField(
            model_name='verse',
            name='verse',
            field=verses.custom_models.Text(max_length=200),
        ),
    ]
