# Generated by Django 3.0.6 on 2020-05-17 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verses', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purportsectiontag',
            unique_together={('verse_id', 'tag', 'start_idx', 'end_idx')},
        ),
        migrations.AlterUniqueTogether(
            name='translationtag',
            unique_together={('verse_id', 'tag')},
        ),
    ]
