# Generated by Django 3.0.6 on 2020-05-28 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('verses', '0002_auto_20200528_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagrequest',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tagrequest_approver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tagrequest',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='tagrequest',
            name='initiator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tagrequest_initiator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tagrequest',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='tagrequest',
            name='parent',
            field=models.CharField(max_length=60),
        ),
    ]
