# Generated by Django 3.0.6 on 2020-06-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verses', '0003_auto_20200528_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='purportsectiontag',
            name='tagger_remark',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='translationtag',
            name='tagger_remark',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
