# Generated by Django 3.0.6 on 2020-06-13 09:29

from django.db import migrations
import verses.custom_models


class Migration(migrations.Migration):

    dependencies = [
        ('verses', '0004_auto_20200601_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='verse',
            name='context',
            field=verses.custom_models.Text(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='verse',
            name='title',
            field=verses.custom_models.Text(max_length=500, null=True),
        ),
    ]
