# Generated by Django 3.0.6 on 2020-06-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verses', '0005_auto_20200613_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag3',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
