# Generated by Django 3.0.6 on 2020-06-16 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verses', '0006_auto_20200615_0720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='verses.Tag')),
            ],
            options={
                'unique_together': {('level', 'name')},
            },
        ),
        migrations.AddField(
            model_name='purportsectiontag',
            name='tag_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='verses.Tag'),
        ),
        migrations.AddField(
            model_name='translationtag',
            name='tag_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='verses.Tag'),
        ),
    ]
