# Generated by Django 3.0.6 on 2020-06-26 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verses', '0008_tag_is_leaf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag2',
            name='parent_tag',
        ),
        migrations.RemoveField(
            model_name='tag3',
            name='parent_tag',
        ),
        migrations.AlterUniqueTogether(
            name='purportsectiontag',
            unique_together={('verse_id', 'tag_name', 'start_idx', 'end_idx')},
        ),
        migrations.AlterUniqueTogether(
            name='translationtag',
            unique_together={('verse_id', 'tag_name')},
        ),
        migrations.DeleteModel(
            name='Tag1',
        ),
        migrations.DeleteModel(
            name='Tag2',
        ),
        migrations.RemoveField(
            model_name='purportsectiontag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='translationtag',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag3',
        ),
    ]
