# Generated by Django 3.0.6 on 2020-05-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'tagger'), (3, 'reviewer')], default=1),
        ),
    ]
